# Megraph GFN for ogbg
CONFIG = {
    "runs": 5,
    "lr": 0.001,
    "weight_decay": 5e-4,
    "e_hidden": None,
    "n_hidden": 300,
    "n_layers": 4,
    "activation": "relu",
    "dropout": 0.5,
    "norm_layer": "layer",
    "epochs": 100,
    "use_input_embedding": True,
    "add_reverse_edges": False,
    "self_loop": True,
    "to_simple_graph": False,
    "max_height": 5,
    "global_pool_methods": ["mean", "max", "att"],
    "cluster_size_limit": 3,
    "pool_node_ratio": 0.5,
    "keep_beta": 1.0,
    "cross_beta": 1.0,
}
