# Megraph GFN for peptides_struct
CONFIG = {
    "runs": 4,
    "drop_last": False,
    # "use_adam": True,
    "lr_scheduler": "plateau",
    "lr_scheduler_indicator": "loss",
    "reduce_factor": 0.5,
    "reduce_patience": 20,
    "min_lr": 1e-5,
    "lr": 0.001,
    "weight_decay": 0.0,
    "e_hidden": None,
    "n_hidden": 160,
    "n_layers": 4,
    "activation": "relu",
    "dropout": 0.0,
    "edgedrop": 0.2,
    "norm_layer": "layer",
    "epochs": 200,
    "train_batch_size": 128,
    "eval_batch_size": 128,
    "stem_beta": 0,
    "branch_beta": 1,
    "global_pool_methods": ["mean"],
    "use_input_embedding": True,
    "add_reverse_edges": True,
    "to_simple_graph": True,
    "max_height": 9,
    "pool_node_ratio": 0.3,
    "keep_beta": 1.0,
    "cross_beta": 0.5,
}
